<?php

namespace App\Models\Audit;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Class AuditRule
 * 
 * @property int $id
 * @property string $key
 * @property string $title
 * @property string $category
 * @property string $severity_default
 * @property bool $is_active
 * @property array|null $config_json
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 */
class AuditRule extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'audit_rules';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<string>
     */
    protected $fillable = [
        'key',
        'title',
        'category',
        'severity_default',
        'is_active',
        'config_json',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'is_active' => 'boolean',
        'config_json' => 'array',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    /**
     * Get the audits generated by this rule.
     */
    public function audits(): HasMany
    {
        return $this->hasMany(SeoAudit::class, 'rule_id');
    }
}
